-- Note: For pg_net to work, the pg_net extension must be enabled.
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Function that calls the send-sms Edge Function
CREATE OR REPLACE FUNCTION notify_user_on_shift_trade() 
RETURNS TRIGGER AS $$
DECLARE
    project_url TEXT := 'YOUR_SUPABASE_PROJECT_URL'; -- E.g. https://abcxyz.supabase.co
    service_role_key TEXT := 'YOUR_SUPABASE_SERVICE_ROLE_KEY';
    payload JSONB;
    request_id BIGINT;
BEGIN
    -- Only notify if the request is pending and proposed to someone
    IF NEW.status = 'pending' AND NEW.proposed_to IS NOT NULL THEN
        
        -- Build the JSON payload to send to the Edge Function
        -- We include the NEW.sms_code that was generated by the BEFORE INSERT trigger
        payload := jsonb_build_object(
            'userId', NEW.proposed_to,
            'messageBody', 'A new shift trade has been proposed to you. Reply YES ' || NEW.sms_code || ' to accept it.'
        );

        -- Make the HTTP POST request to the Edge Function using pg_net
        -- Warning: project_url and service_role_key need to be set in your Supabase project Vault
        -- or hardcoded here for testing. It's safer to use Vault.
        SELECT net.http_post(
            url := project_url || '/functions/v1/send-sms',
            headers := jsonb_build_object(
                'Content-Type', 'application/json',
                'Authorization', 'Bearer ' || service_role_key
            ),
            body := payload
        ) INTO request_id;
        
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute the function after insert on shift_trades
DROP TRIGGER IF EXISTS trigger_notify_on_trade ON public.shift_trades;
CREATE TRIGGER trigger_notify_on_trade
AFTER INSERT ON public.shift_trades
FOR EACH ROW
EXECUTE FUNCTION notify_user_on_shift_trade();
